---
- name: Copy jdk installer
  win_copy: src="{{ jdk_exe }}" dest="C:\\jdk-{{ java_version }}u{{ jdk_version }}-windows-x64.exe"
- name: Install jdk
  win_package:
    path: "C:\\jdk-{{ java_version }}u{{ jdk_version }}-windows-x64.exe"
    product_id: "{{ jdk_id }}"
    arguments: '/s ADDLOCAL="ToolsFeature,SourceFeature,PublicjreFeature"'

