---
- name: Download jdk
  win_shell: |
    $source = "http://download.oracle.com/otn-pub/java/jdk/{{ java_version }}u{{ java_build }}-b{{ java_internal_build }}/jdk-{{ java_version }}u{{ java_build }}-windows-x64.exe"
    $destination = "C:\jdk-{{ java_version }}u{{ java_build }}-windows-x64.exe"
    $client = new-object System.Net.WebClient 
    $cookie = "oraclelicense=accept-securebackup-cookie"
    $client.Headers.Add([System.Net.HttpRequestHeader]::Cookie, $cookie) 
    $client.downloadFile($source, $destination)
  args:
    creates: "C:\\jdk-{{ java_version }}u{{ java_build }}-windows-x64.exe"
- name: Install jdk
  win_package:
    path: "C:\\jdk-{{ java_version }}u{{ java_build }}-windows-x64.exe"
    product_id: "{{ product_id }}"
    arguments: '/s ADDLOCAL="ToolsFeature,SourceFeature,PublicjreFeature"'
- name: Get installed java version
  win_command: '"C:\\Program Files\\Java\\jdk1.{{ java_version }}.0_{{ java_build }}\\bin\\java" -version'
  register: installed_java_version
- assert:
    msg: "Incorrect java version found: {{ installed_java_version.stderr }}"
    that:
      - "java_version in installed_java_version.stderr"
      - "java_build in installed_java_version.stderr"
