---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/Debian.yml"
  when: redis_package is not defined or redis_path is not defined
- name: install redis package
  package: name={{redis_package}}
- name: copy configs
  template: src={{ item }}.j2 dest={{redis_path}}/{{ item }}.conf
  with_items:
    - redis
    - sentinel
  notify: redis restart
- name: redis enable
  service: name={{redis_package}} enabled=yes
- name: redis start
  service: name={{redis_package}} state=started
- name: copy sentinel service
  template: src=sentinel.service.j2 dest=/etc/systemd/system/multi-user.target.wants/redis-sentinel.service
  notify: restart sentinel
