---
- name: nginx restart
  service: name=nginx state=restarted
  notify: check nginx

- name: check nginx
  connection: local
  uri:
    url: "http://{{ domain_name }}/"
    method: POST
    body: "url=http:%2F%2Fgoogle.com"
    HEADER_Content-Type: "application/x-www-form-urlencoded"
